apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2019-09-26T03:54:56Z"
  name: cisco
  resourceVersion: "113578"
  selfLink: /api/v1/namespaces/cisco
  uid: a634ab82-bb43-495c-8467-2b00f7db4f71
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
